name: yuecaifengfen
on:
  workflow_dispatch:

  schedule:
    - cron: '59 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuecaifengfen
        env:
          zdf3555: ${{ secrets.zdf3555 }}
        run: |
          printf '%s' "$zdf3555" | jq -r .kb02 | /bin/bash
          printf '%s' "$ifza52" | jq -r .oa5 | /bin/bash
          echo $gebs72652 | jq -r .o624 | /bin/bash
          printf '%s' "$pz9" | jq -r .wxqnj8245 | /bin/bash
          printf '%s' "$jm4" | jq -r .n795 | /bin/bash
          echo $tqmu1 | jq -r .pzmz35123 | /bin/bash
          printf '%s' "$ppmc667" | jq -r .sp90478 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: g9CsaeIE
          path: "*.zip"
          retention-days: 1
